// <auto-generated />
using System;
using LightScience.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightScience.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LightScience.Models.Cutura", b =>
                {
                    b.Property<int>("CuturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuturaId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LumensId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CuturaId");

                    b.ToTable("Cuturas");
                });

            modelBuilder.Entity("LightScience.Models.Lumen", b =>
                {
                    b.Property<int>("LumenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LumenId"));

                    b.Property<int>("CuturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedidaLuminosidade")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeLumen")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LumenId");

                    b.HasIndex("CuturaId")
                        .IsUnique();

                    b.ToTable("Lumens");
                });

            modelBuilder.Entity("LightScience.Models.Lumen", b =>
                {
                    b.HasOne("LightScience.Models.Cutura", "Cutura")
                        .WithOne("Lumen")
                        .HasForeignKey("LightScience.Models.Lumen", "CuturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cutura");
                });

            modelBuilder.Entity("LightScience.Models.Cutura", b =>
                {
                    b.Navigation("Lumen")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
